name: Generate 3D contribution profile

on:
  schedule:
    - cron: "15 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate 3D profile
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: tungtimo0808

      - name: Commit and push 3D profile
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate 3D contribution profile"
          add: "profile-3d-contrib/*.svg"
